@url = https://obscure-engine-wq6pq6x5rjvc59pw-8080.app.github.dev

GET {{url}}/livros

###
GET {{url}}/livros/3

###
POST {{url}}/livros
Content-Type: application/json

{
    "titulo": "Novo Teste",
    "id_genero" : 1,
    "autores" : [{"id" : 1}]
}

###
PUT {{url}}/livros/5
Content-Type: application/json

{
    "titulo": "Livro 5 Alterado",
    "generos" : "Genero Alterado",
    "autores" : "Autor Alterado"
}

###
DELETE {{url}}/livros/5